### PR TITLE
Add repo.commits call

### PR DESCRIPTION
**Pull request by nitay**
Support for getting all commits from a repo, with optional filters.

### CODE REVIEW

**Comment by nitay** [comment]
@softprops any interest in this? also the test failure seems unrelated to my PR?

**Comment by softprops** [comment]
Now that java 7 has reached its end of life http://www.infoq.com/news/2015/05/Oracle-Ends-Java-7Public-Updates and java 8 has a nice time library out of the box https://docs.oracle.com/javase/8/docs/api/java/time/package-summary.html. how would you feel about using those time interfaces as they are likely to be available rather than adding a new runtime dependency?

**Comment by nitay** [comment]
@softprops done

**Review by jroc09 — COMMENTED** [review]
What needs to be added to pass build

**Pull request merged**
